name: build all

on:
  push:
    branches: [ "trunk", "gretel-actions" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Requirements
      run: |
        sudo apt -qqy update
        sudo apt -qqy install avr-libc binutils-avr gcc-avr wget unzip

    - name: Install Device Family Pack
      run: |
        ./make dfp

    - name: Compile All
      run: |
        ./make
        echo "ARTIFACT_NAME=${GITHUB_WORKFLOW}-${GITHUB_REF_NAME}-$(git rev-parse --short ${GITHUB_SHA})-${GITHUB_RUN_NUMBER}" >> "${GITHUB_ENV}"

    - name: Store Artifacts
      uses: actions/upload-artifact@master
      with:
        name: ${{ env.ARTIFACT_NAME }}
        if-no-files-found: error
        path: |
          hex/*.hex
