name: build all

on:
  push:
    branches: [ "trunk", "gretel-actions" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Requirements
      run: |
        sudo apt -qqy update
        sudo apt -qqy install avr-libc binutils-avr gcc-avr unzip wget

    - name: Cache Atmel DFPs
      id: cache-dfp
      uses: actions/cache@v3
      env:
        cache-name: cache-dfp-files
      with:
        path: arch/dfp
        # new cache whenever the dfp-install script changes
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('bin/dfp-install.sh') }}

    - name: Install Atmel DFPs
      if: steps.cache-dfp.outputs.cache-hit != 'true'
      run: |
        ./make dfp

    - name: Compile All
      run: |
        ./make
        echo "ARTIFACT_NAME=${GITHUB_WORKFLOW}-${GITHUB_REF_NAME}-$(git rev-parse --short ${GITHUB_SHA})-${GITHUB_RUN_NUMBER}" >> "${GITHUB_ENV}"

    - name: Store Artifacts
      uses: actions/upload-artifact@master
      with:
        name: ${{ env.ARTIFACT_NAME }}
        if-no-files-found: error
        path: |
          hex/*.hex
